### ISSUE TITLE
modprobe error during startup of container

### ISSUE THREAD

**Issue by haraldmeyer** [hwdsl2/docker-ipsec-vpn-server#103]
I loaded af_key before creating the container (using the current image). When starting the container I get the following in the log: 

```
================================================

modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/2.6.32-696.23.1.el6.x86_64/modules.builtin.bin'
Redirecting to: /etc/init.d/ipsec start
Starting pluto IKE daemon for IPsec: Initializing NSS database

.....
xl2tpd[1]: Not looking for kernel SAref support.
xl2tpd[1]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)
xl2tpd[1]: xl2tpd version xl2tpd-1.3.12 started on f4640907dddb PID:1
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701

```

Any idea what the problem is? Is it related to af_key or something else?

**Comment by hwdsl2** [comment]
@haraldmeyer Hello! Make sure that you bind the /lib/modules directory in the “docker run” command, like this: `-v /lib/modules:/lib/modules:ro ` This is mentioned in the README.

The modprobe error indicates that the container is unable to load the af_key kernel module, and this is typically caused by not binding the directory above, or the kernel modules that matches your running kernel may be missing on your host under /lib/modules. You’ll need to reinstall your kernel if that is the case.

If you did successfully load the af_key module on the Docker host, however, you can try to connect a VPN client to test if it works.
