### ISSUE TITLE
Can't connect after Windows update.

### ISSUE THREAD

**Issue by Tjird** [hwdsl2/docker-ipsec-vpn-server#108]
I can't connect to de VPN server after the windows update. 

The L2TP connection attempt failed because the security
layer encountered a processing error during initial
negotiations with the remote computer.

That is the message that I get. The windows version is Windows 10 version 1809.

**Comment by hwdsl2** [comment]
@Tjird Re-apply the fix for Windows Error 809 and reboot. See [1]. This error could also indicate that the connection attempt did not reach your VPN server [2]. In addition, try deleting and re-creating the VPN connection [3], double check to make sure the VPN credentials are typed correctly.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting
[2] https://github.com/hwdsl2/setup-ipsec-vpn/issues/481#issuecomment-437714296
[3] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md
