### ISSUE TITLE
browser just shows connecting when going to restricted sites

### ISSUE THREAD

**Issue by mehrunrasoli** [hwdsl2/docker-ipsec-vpn-server#109]
Hello there!

I have configured the VPN successfully and on the client side, it connects. but while it changes my IP, still I can't connect to the restricted sites by the internet provider.

I think there should be a way to not only change the IP but also proxy all my traffic through the server

**Comment by hwdsl2** [comment]
@mehrunrasoli Hello! What is your VPN client's operating system? Traffic should be proxied through the VPN server while connected. Test if you can visit the site in question from your VPN server itself. You may use `wget` or `curl` to test. If not, then your VPN server provider also restricts the site. Otherwise, clear the DNS cache on your VPN client (search on Google) and reboot.

**Comment by hwdsl2** [comment]
@mehrunrasoli Note that for some countries traffic may be blocked or interfered with even when connected to the VPN server. You might want to instead look into alternative solutions such as Shadowsocks.

**Comment by mehrunrasoli** [comment]
WOW Thanks to reponse so quick!

> You may use wget or curl to test.
it works.

> clear the DNS cache on your VPN client
Still the same issue.

> Note that for some countries traffic may be blocked or interfered with even when connected to the VPN server.

Exactly, I should test another tool. thanks man!
