### ISSUE TITLE
How to modify to use IKEv2 ?

### ISSUE THREAD

**Issue by jason404** [hwdsl2/docker-ipsec-vpn-server#138]
I would prefer to use IKEv2 for connection from my router and it is required for iOS.  How do I modify this docker image to use IKEv2 instead?  Would it be difficult?  Thanks.

**Comment by hwdsl2** [comment]
@jason404 Hello! On iOS I think you can also use IPsec/L2TP and Cisco IPsec mode.

To modify your Docker container to use IKEv2, first start a Bash shell in the running container [1], then follow the steps in this IKEv2 tutorial [2].

This method is not ideal, because on container restart, the `/etc/ipsec.conf` will be overwritten by `run.sh` and your IKEv2 config section will not persist. You may get around this by commenting out the relevant sections in `/opt/src/run.sh` from inside the container. Also, you may want to backup your IKEv2 configuration (certs, keys, etc.) stored in the "/etc/ipsec.d" folder to a location outside the container, because if you re-create the container you'll lose those configuration.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#bash-shell-inside-container
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
