### ISSUE TITLE
Configure VPN to go through proxy

### ISSUE THREAD

**Issue by kennyparsons** [hwdsl2/docker-ipsec-vpn-server#140]
@hwdsl2 I have not been able to find any info on how to configure the vpn to go through a proxy. I am running a proxy container to log my traffic, and I'm using your vpn docker to bring in all my traffic. So far, your container is working perfectly, just hitting a road block on this proxy part.

How can I accomplish this?

**Comment by hwdsl2** [comment]
@kennyparsons Hello! Due to the Docker architecture, it is difficult to forward traffic between containers (the proxy in your use case). You may use the "host" network mode (refer to #133) to get around this restriction, however that mode is not recommended for this Docker container, because it modifies the IPTables rules on your Docker host, instead of IPTables rules in the container.

To actually forward the traffic to the proxy, you can try IPTables FORWARD and/or NAT rules. For details, please ask on the Libreswan/strongSwan users mailing list or the Docker community.

**Comment by kennyparsons** [comment]
@hwdsl2 would it be possible to build my own image with your docker image and a proxy image all in one container?

**Comment by hwdsl2** [comment]
@kennyparsons Yes, please refer to: https://github.com/hwdsl2/docker-ipsec-vpn-server#build-from-source-code

**Comment by kennyparsons** [comment]
Thank you for the quick responses!
