### ISSUE TITLE
Connect to parent machine's network

### ISSUE THREAD

**Issue by adryd325** [hwdsl2/docker-ipsec-vpn-server#144]
Sorry if I don't know that much, but I'm looking for a way to configure the service to connect clients to the host machine's sub net and have the DHCP server of my firewall handle IP address assignments.

I want to be able to connect to devices connected over VPN while on my Host's network.
I'm assuming the person who issued #142 is looking for the same or similar solution as me

**Comment by hwdsl2** [comment]
@adryd325 Hello! Due to Docker's isolation of containers, it is generally difficult to either connect clients to the Docker host's subnet, or connect from the Docker host's network to devices connected over VPN. See similar issues [1][2].

If not using Docker, see [3] for how to access the VPN server's subnet by adding IPTables rules. However, you may not be able to let the DHCP server handle IP assignments for VPN clients.

Unfortunately, I am not aware of a good solution for your use case. Maybe a site-to-site VPN would help. I suggest that you ask the VPN experts on the Libreswan or strongSwan users mailing lists.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/141
[2] https://github.com/hwdsl2/setup-ipsec-vpn/issues/554
[3] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#access-vpn-servers-subnet

**Comment by adryd325** [comment]
I guess what I'm looking for is more of a client to site configuration (where devices on the site can access the client), where the client behaves as if it were just another device on the network. I don't think there's a quick change that can be made to the config to make that possible. 

Unfortunately I don't have access to my firewall, only port forwarding, so I can't use a native firewall function for a vpn
