### ISSUE TITLE
problem with only with google search engine site "www.google.com"

### ISSUE THREAD

**Issue by imannasr** [hwdsl2/docker-ipsec-vpn-server#151]
Hello sir,

thanks for you project that is very good and helpful. but in first use we can access to www.google.com but after some time we can't load www.google.com. this problem is only for google and all of other sites are working very well.

is tiny problem is for what? can you guide me for this? 

with best regards
Iman

**Comment by hwdsl2** [comment]
@imannasr Hello! If the issue is only with `www.google.com`, then it is most likely that your VPN server itself has problems accessing this website. You may check this by doing a `wget` or `curl` from your VPN server. Another possible cause is cached incorrect DNS entries on your VPN client for this site, which you can resolve by clearing the DNS cache on your device and reboot.

**Comment by imannasr** [comment]
OK Thanks.
But i changed my DNS setting in server to 1.1.1.1 and the problem solved very good.
thanks.
