### ISSUE TITLE
Add More VPN USER

### ISSUE THREAD

**Issue by pharrellxx3** [hwdsl2/docker-ipsec-vpn-server#162]
Documents write  is wrong
`
VPN_ADDL_USERS=additional_username_1 additional_username_2
VPN_ADDL_PASSWORDS=additional_password_1 additional_password_2
`
but can't pass verify.

The finally edit,correct write like this
`
VPN_ADDL_USERS="additional_username_1 additional_username_2"
VPN_ADDL_PASSWORDS="additional_password_1 additional_password_2"
`

**Comment by hwdsl2** [comment]
@pharrellxx3 Hello! Thanks for bringing this up. The documentation is correct because Docker interprets the variable values in the `env` file literally, no quotes needed. Give it a try yourself and you’ll see.

On the other hand, if you are blind mounting the `env` file (see advanced usage section in the README), single quotes around variable values are required.
