### ISSUE TITLE
can't modprobe af_key in debian8

### ISSUE THREAD

**Issue by rainysia** [hwdsl2/docker-ipsec-vpn-server#2]
Hi mate,

I use debian8 (jessie) amd64 version, kernel 4.1.5-x86_64-linode61.
and can't modprobe af_key, 

`modprobe af_key`
`modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.1.5-x86_64-linode61/modules.dep.bin'`

Do you know how to add this? or maybe i need to rebuild kernel and enable IPSEC?

Thanks.

**Comment by hwdsl2** [comment]
Hi @rainysia. On Linode you need to use a Debian-provided kernel via PV-GRUB instead of Linode-provided kernel, where some modules may be missing. Please refer to [1] for detailed steps. Scroll down to the Debian 8 section.

[1] https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distributionsupplied-kernel-with-pvgrub

**Comment by rainysia** [comment]
Thanks @hwdsl2, It works
