### ISSUE TITLE
How to add/del users automatically？

### ISSUE THREAD

**Issue by wolfwithsheep** [hwdsl2/docker-ipsec-vpn-server#213]
Dear, how to add/del users automatically? And how to check the users's status? 
Looking forward to your reply, thanks！

**Comment by hwdsl2** [comment]
@wolfwithsheep Hello! Please refer to the README. You may use the `env` file [1] to specify multiple users. If you bind mount the env file when creating the Docker container, you will be able to restart the Docker container to take effect (instead of recreating it) after editing users in your `env` file. Check the container logs [3] to see the list of users for the VPN.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#environment-variables
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server#bind-mount-the-env-file
[3] https://github.com/hwdsl2/docker-ipsec-vpn-server#retrieve-vpn-login-details

**Comment by wolfwithsheep** [comment]
@hwdsl2 Thanks for your replay again! I am working on it as you said
