### ISSUE TITLE
How to support extra configuration options for macOS Big Sur problem

### ISSUE THREAD

**Issue by yegor256** [hwdsl2/docker-ipsec-vpn-server#225]
Check this out https://serverfault.com/questions/1045012/configuring-l2tp-vpn-to-use-with-ios-14-and-macos-big-sur The latest version of macOS (11.2 Big Sur) is not working with VPN anymore. There should be some possibility to configure additional options.

[This page](https://www.reddit.com/r/MacOSBeta/comments/ih22h9/vpn_l2tp_over_ipsec_stopped_working_after/g8ora2x/?utm_source=reddit&utm_medium=web2x&context=3) says that "Switching the SHA-256 HMAC output from 96 to 128 bits on the server should fix this issue" How can I do this?

**Comment by hwdsl2** [comment]
@yegor256 Hello! As indicated in the link you mentioned, this issue only occurs if you have `sha2-truncbug=yes` in `/etc/ipsec.conf` on the VPN server, and changing `sha2-truncbug=yes` to `sha2-truncbug=no` in that file, and run `sudo service ipsec restart` fixes it.

For this Docker image, `sha2-truncbug=no` has been the default value since 2019-09-22 (57fa056). Therefore it is not affected unless you are using a very old version of this image, in which case you can update to the latest version [1].

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#update-docker-image

**Comment by yegor256** [comment]
@hwdsl2 indeed, the latest Docker image works just fine
