### ISSUE TITLE
VPN DNS name

### ISSUE THREAD

**Issue by niksy** [hwdsl2/docker-ipsec-vpn-server#241]
What is the purpose of `VPN_DNS_NAME` environment variable?

If I set it to my FQDN, I still need to update `A` DNS records either manually (e.g. I’m using static IP address) or automatically with DNS updater service (if I’m using dynamic IP address). Is this something container related?

**Comment by hwdsl2** [comment]
@niksy Hello! You are correct that DNS records will need to be updated after setting VPN_DNS_NAME.

The primary purpose of this variable is for generating the server certificate inside the container for IKEv2. When connecting using IKEv2 mode, the VPN server must have a certificate that contains the FQDN specified in the VPN server address field of the VPN client, otherwise the client may refuse to connect.
