### ISSUE TITLE
Connect many accounts to VPN

### ISSUE THREAD

**Issue by tomosia-phuongvo** [hwdsl2/docker-ipsec-vpn-server#246]
**Describe the issue**
   Currently, my VPN created many accounts with usernames and passwords for all members of my company. But I have a problem when members use VPN on their device connect to my VPN. Only the one connects to VPN and other members
can’t connect at this moment. Please help me fix a problem.
**Server**
Docker host OS: Ubuntu 20.04.2 LTS
**Client**
Device: Android Samsung Galaxy s10 plus
OS: Android 11
VPN mode: L2tp/IPsec

**Comment by hwdsl2** [comment]
@tomosia-phuongvo Hello! As mentioned in the important notes [1], due to an IPsec/L2TP limitation, if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only [IPsec/XAuth mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md) or [IKEv2 mode](https://github.com/hwdsl2/docker-ipsec-vpn-server#configure-and-use-ikev2-vpn).

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#important-notes
