### ISSUE TITLE
Publish Versioned images

### ISSUE THREAD

**Issue by Emeryao** [hwdsl2/docker-ipsec-vpn-server#255]
Hi Doc, here is my story

I started use this awesome work back in 2020 to setup a work-from-home server with frps/frpc on a VPS since I don't have a public/static IPv4 address and it worked perfectly on Windows/ios/Android

but early in this August I updated the image `hwdsl2/ipsec-vpn-server` to the latest version and I can't connect to the VPN server any more so I want to revert the image to an older version I tried to lookup the push history on `quay.io` but no working images found

So can we push a *versioned* tag to the container registry besides of `latest`/`debian` ?

**Comment by hwdsl2** [comment]
@Emeryao Hello! Thank you for your suggestion. This had been asked before, and I decided not to push versioned images due to the overhead related to maintaining them. There have been very few backward incompatible changes in this project. If you find a bug in the latest image, please provide details (e.g. logs [1]) and I'd be happy to look into and fix it.

On the other hand, you can easily build an older revision of this project. Clone the project to your local machine, check out an older Git revision, then follow the steps in build from source code [2] to create a local Docker image. Then re-create the VPN container from the local image.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#enable-libreswan-logs
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server#build-from-source-code

**Comment by Emeryao** [comment]
I tried to build the image from source but you-know-why the gfw so I failed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
