### ISSUE TITLE
How to use IPSec VPN on Linux

### ISSUE THREAD

**Issue by WJHPrince** [hwdsl2/docker-ipsec-vpn-server#28]
I successfully setup my IPSec server by using your docker image. However I can't link to it on Linux. 
I use `vpnc` to setup link. Here is the config file:
``` 
IPSec gateway xxx.xxx.xxx.xxx
IPSec ID <group-id>
IPSec secret *******
IKE Authmode psk
Xauth username xxx
Xauth password xxx
```
What is IPSec ID? 
P.S.打英语好麻烦，如果可以的话能不能烦请用中文？

**Comment by hwdsl2** [comment]
@WJHPrince Hello! The IPsec ID is the "group name" in IPsec/XAuth "aggressive mode". This is not supported by the default configuration - you must edit `/etc/ipsec.conf` for it to work. Please refer to the following issues [1] [2] [3] for details. Read all comments in these issues. Also read the important notes [4].
   
Instead of the above, an easier alternative is to connect via IPsec/L2TP. You can find more details in [5].

P.S. Feel free to use Chinese in your reply.

[1] hwdsl2/setup-ipsec-vpn#152
[2] hwdsl2/setup-ipsec-vpn#121
[3] hwdsl2/setup-ipsec-vpn#70
[4] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示
[5] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#linux
