### ISSUE TITLE
disable l2tp protocol

### ISSUE THREAD

**Issue by whoami-idk** [hwdsl2/docker-ipsec-vpn-server#339]
**Describe the enhancement request**
How can i disable l2tp protocol ?

**Is your enhancement request related to a problem? Please describe.**
ipsec trafficstatus command not showing username for current l2tp connections.

```
root@m:~# docker exec -it ipsec-vpn-server ipsec trafficstatus
006 #4048: "l2tp-psk"[383] 111.111.111.111, type=ESP, add_time=1672900514, inBytes=599, outBytes=655, maxBytes=2^63B, id='192.168.1.200'
root@m:~# docker exec -it ipsec-vpn-server ipsec trafficstatus
006 #4050: "xauth-psk"[2648] 111.111.111.111, username=test, type=ESP, add_time=1672900538, inBytes=5584, outBytes=23554, maxBytes=2^63B, lease=192.168.43.10/32
root@m:~# docker exec -it ipsec-vpn-server ipsec trafficstatus
006 #4052: "ikev2-cp"[59] 111.111.111.111, type=ESP, add_time=1672900551, inBytes=4572, outBytes=23132, maxBytes=2^63B, id='CN=test, O=IKEv2 VPN', lease=192.168.43.10/32
```
**l2tp-psk = not defined**
xauth-psk = username=test
ikev2-cp = CN=test

**Comment by hwdsl2** [comment]
@whoami-idk Hello! It looks like you are trying to get the connecting VPN client's username for IPsec/L2TP mode. `ipsec trafficstatus` will not show this information, because user authentication is done by xl2tpd/ppp, not IPsec (Libreswan). This feature is outside the scope of this project and not supported. For more information, refer to [this issue](https://github.com/hwdsl2/setup-ipsec-vpn/issues/166).
