### ISSUE TITLE
TCP is broken

### ISSUE THREAD

**Issue by sticky333** [hwdsl2/docker-ipsec-vpn-server#35]
Hi guys. I've installed vpn with a docker container behind a NAT. I'm trying to connect to my network and I get some problems with tcp connections from shrew. Ping works fine but if I connect through TCP after a while tcp is broken. From my client I see that packets a going out through vpn server but not coming back. At the destination host I see a lot of retransmission packets. Can you help me to solve this issue? p.s. from MacOS everything works well but not from shrew.

**Comment by hwdsl2** [comment]
@sticky333 Hello! Aside from possible network issues (maybe try a different server provider?), because the Shrew Soft VPN client hasn't been updated for a long time, it is likely to contain bugs and it's impossible for us to troubleshoot the issue for you. You may want to instead try the IPsec/L2TP mode using the built-in Windows client [1]. 

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md

**Comment by sticky333** [comment]
Hello, thank you for your reply. I've solved the issue with broken TCP. The main reason is that mtu on interface has been installed to 1500 and as a result icmp was working but tcp not. Anyway, I've installed additional openswan packages to my host and now I can connect to my VPN using network-manager without shrew or any additional software. p.s. As I understood, I can't use L2TP mode because of NAT behind the server.
