### ISSUE TITLE
win10 cannot connect

### ISSUE THREAD

**Issue by remini1998** [hwdsl2/docker-ipsec-vpn-server#37]
It's caused by the docker instance do not support MS-CHAPv2 which is a 
Add 
`+mschap-v2`
to
> /etc/ppp/options.l2tpd 

in 
> run.sh 

can solve the problem

**Comment by hwdsl2** [comment]
@remini1998 Thanks for contributing. Actually, the VPN currently works fine with Windows 10 as a client. Note that CHAP is required instead of MS-CHAPv2. This is mentioned in the client configuration instructions [1], in step 11.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows

**Comment by remini1998** [comment]
Thanks for your tech support. :D
In the newer version of windows 10, it's not convenient to change the setting. 
Is there some further consideration to not support MS-CHAPv2 which is the default VPN setting of win10?
