### ISSUE TITLE
[Question] How hard would it be to configure this vpn server to give access to the server local network ( as it already does ) but don't route traffic outside server local network through the server ?

### ISSUE THREAD

**Issue by iTris666** [hwdsl2/docker-ipsec-vpn-server#417]
**Checklist**

- [ X] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue), and did not find a similar enhancement request
- [X ] This enhancement request is about the IPsec VPN server Docker image, and not IPsec VPN itself
- [ X] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [X ] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [X ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [X ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
[Question] How hard would it be to configure this vpn server to give access to the server local network ( as it already does ) but don't route traffic outside server local network through the server ?

I want to access my home network remotely and securely ( which this docker image provides)
but I don't want all traffic from my client that have nothing to do with my home network to go through this vpn even when I'm connected to the vpn. It can be called bridge vpn or split vpn depending on the source.

Thanks a lot for this amazing docker !

**Comment by hwdsl2** [comment]
@iTris666 Hello! First, thank you for your support! The feature you mentioned is called split tunneling.

First [start a Bash shell inside the container](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#bash-shell-inside-container), then refer to the steps in the [split tunneling](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#split-tunneling) section in advanced usage. When finished, `exit` the container and run `docker restart ipsec-vpn-server`.

Note that when editing `/etc/ipsec.conf`, you can also edit the corresponding section in `/opt/src/run.sh`, so that the changes can persist after a container restart.
