### ISSUE TITLE
Improve the default settings

### ISSUE THREAD

**Issue by JamesHagerman** [hwdsl2/docker-ipsec-vpn-server#44]
I'll admit I'm no VPN expert, but it seems like the defaults for this VPN could be improved quite a bit.

If nothing else, maybe add a note as to why these cipher were picked as the defaults?
```
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
```

Thanks

**Comment by hwdsl2** [comment]
@JamesHagerman Hello! Thanks for the suggestion. The default IKE ciphers had been selected to be as universal as possible (i.e. trying to be compatible with Windows, macOS, Linux, iOS, Android, etc.) The `modp1024` part is required because in recent Libreswan versions, `modp1024` was removed from the default which broke compatibility with Windows clients, unless this part is added. Finally, the `aes256-sha2_512` part was added to improve compatibility with Android 6 and 7 clients [1].

[1] https://libreswan.org/wiki/FAQ#Using_SHA2_256_for_ESP_connection_establishes_but_no_traffic_passes_.28especially_Android_6.0.29
