### ISSUE TITLE
In ubuntu 18.04, it can not startup

### ISSUE THREAD

**Issue by SOmeONee** [hwdsl2/docker-ipsec-vpn-server#77]
In container ,when run ipsec , error is : 
FATAL ERROR: Failed to bind bcast socket in init_netlink() - Perhaps kernel was not compiled with CONFIG_XFRM. Errno 1: Operation not permitted

**Comment by fl0wfr** [comment]
xl2tpd is broken with kernel 4.15, see here : https://bugs.launchpad.net/ubuntu/+source/xl2tpd/+bug/1760796

**Comment by SOmeONee** [comment]
Bad news. Thanks.

**Comment by sharipov-ru** [comment]
@SOmeONee 

You can apply workaround from development version of xl2tpd as follows:

first, run this on your host:

```
docker exec -it ipsec-vpn-server bash
```

then inside a container:

```
apt-get install -y build-essential git libpcap0.8-dev
git clone -b 1.3.12 https://github.com/xelerance/xl2tpd.git
make
sudo cp xl2tpd /usr/sbin/xl2tpd
service xl2tpd restart
```

Then container restarts and you'll be able to connect (at least it's working for me, Ubuntu 18.04 on Digitalocean + L2TP/IPsec router client)

This is dirty workaround since it downloads a lot of packages for your container, but at least it works and may be an option for you.

**Comment by fl0wfr** [comment]
Dirty workaround but that will make it until image gets an update.
Thanks @sharipov-ru !

**Comment by SOmeONee** [comment]
@sharipov-ru thanks very much
